\documentclass{article}
\usepackage{hyperref}
\usepackage[margin=1in]{geometry}
\usepackage{booktabs}


\begin{document}
% \SweaveOpts{concordance=TRUE}

\title{Provenance model methods and results outline}
\author{Christophe}
\date{\today}
\maketitle


<<setup, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE>>=
library(xtable)
source("/Users/christophe_rouleau-desrochers/github/egret/analyses/analyseSeedCues/provenance/modelingCues.R")
dmore1prov <- read.csv("/Users/christophe_rouleau-desrochers/github/egret/analyses/output/moreThan1Prov.csv")

sigmas <- names(fit_nophy_noforcing)[grepl("sigma", names(fit_nophy_noforcing))]
fitdf_noF <- as.data.frame(fit_nophy_noforcing)

fitdf_noF[, sigmas]

sig_sum <- data.frame(
  prm = colnames(fitdf_noF[, sigmas]),
  mu  = round(sapply(fitdf_noF[, sigmas], mean), 3),
  p05 = round(sapply(fitdf_noF[, sigmas], quantile, probs = 0.05), 3),
  p25 = round(sapply(fitdf_noF[, sigmas], quantile, probs = 0.25), 3),
  p75 = round(sapply(fitdf_noF[, sigmas], quantile, probs = 0.75), 3),
  p95 = round(sapply(fitdf_noF[, sigmas], quantile, probs = 0.95), 3),
  row.names = NULL
)

@

% <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
\section{Methods}
% <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
\begin{enumerate}
\item First, we selected all the datasetIDstudy that had more than one provenance per species across the whole egret database (nrow $n = $ \Sexpr{nrow(dmore1prov)}. Second, we ran Victor's decision rules which yields \Sexpr{nrow(newd)} rows of data. Third, we cleaned the dataset before fitting the model with forcing, yielding \Sexpr{nrow(modeld)} rows of data. %emw11Aug: Did you select the studies BEFORE or after Victor's decision rules? If it is after, the I would write: After applying Victor's decision rules and cleaning the dataset, we selected all the .... (right now, it's not clear). Since you don't ref your R files above, I would note them in the comments here. 

\item We fit the provenance model with and without forcing first, compared model estimates and moved on with the model without forcing with chilling and time as the main predictors. See the section `comparing models' below for more details. %emw11Aug: I would show the equation... I can write it in tex for you if you need help and point me to the Stan file. 

\item We compared the no-forcing model with the restricted (only the data with forcing information) versus the full dataset

\end{enumerate}

% <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
\section{Results}
% <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
For the dataset that includes forcing (henceforth referred to as `restricted'), we have \Sexpr{length(unique(modeld$genusspecies))} single species from \Sexpr{length(unique(paste(modeld$datasetID, modeld$study, sep = "")))}. For the dataset without forcing (full),
\begin{enumerate}

%-------------------------------------------------------------------------------
\subsection*{Comparing models}
\item{Did forcing change the germination response?}
%emw11Aug: better to have two subsections, one `comparing models' and there I would include any results from the forcing only model.... one `results from selected model' or such. 
%-------------------------------------------------------------------------------
  \begin{enumerate}
  \item We fitted the provenance model with forcing and without forcing. %emw11Aug: Don't repeat....
  
  \item Forcing does not seem to explain the variation between the no-forcing and forcing models. % Tell me how they differ before you tell me this. 
  Neither the maximum temperature (Figure \ref{fig:maxGermTemp}), the number of unique germination treatments (Figure \ref{fig:uniqueGermTemp}) or the temperature interval seem to explain the observed variation (Figure \ref{fig:germTempInterval}) between the restricted vs full dataset.

  \item The estimates were unchanged when fitting the no-forcing model with the most restricted data ($n =$ \Sexpr{nrow(modeld)}) and the full dataset ($n =$ \Sexpr{nrow(modeld_noforc2)}). 
  
  \item We fitted the model on the most restricted dataset, with and without provenance, which did not change the estimates (Figure \ref{fig:provNoProv})
  \end{enumerate}

%-------------------------------------------------------------------------------
\item{How did time, chilling and forcing impact germination?}
%-------------------------------------------------------------------------------
\textit{Below are for the model that includes forcing. We need to change the x axis on the mu plots.}
  \begin{enumerate}
  \item Forcing had little effects on species, but increased germination for \emph{Maackia taiwanensis} and \emph{Betula utilis} and \emph{Picea glauca} (Figure \ref{fig:muForcing}).
  
  \item Chilling increased germination for most species with huge variations. Four species probability to germinate decreased in response to chilling   (Figure \ref{fig:muChilling}).
  
  \item Time had a similar trend to forcing, with some more species increasing germination in response to time. Most of them didn't shift (Figure \ref{fig:muTime}).
  
\end{enumerate}

%-------------------------------------------------------------------------------
\item Provenance model with chilling and time, not forcing
%-------------------------------------------------------------------------------
  \begin{enumerate}
  
  \item Germination varied more across species ($\sigma$ =
  \Sexpr{sig_sum$mu[sig_sum$prm == "sigma_a"]} (UI:
  \Sexpr{sig_sum$p05[sig_sum$prm == "sigma_a"]},
  \Sexpr{sig_sum$p95[sig_sum$prm == "sigma_a"]})) than across provenances ($\sigma$ =
  \Sexpr{sig_sum$mu[sig_sum$prm == "sigma_a_prov"]} (UI:
  \Sexpr{sig_sum$p05[sig_sum$prm == "sigma_a_prov"]},
  \Sexpr{sig_sum$p95[sig_sum$prm == "sigma_a_prov"]}))
  
  \item We show global germination responses across all species as a function of chilling (Figure \ref{fig:respCurveChilling}) and time (Figure \ref{fig:respCurveTime}).
  
  \end{enumerate}
  
\end{enumerate}

% Provenance model comparison with model without provenance
\begin{figure}[!ht]
\includegraphics[width=0.7\textwidth]{../../analyses/analyseSeedCues/provenance/figures/11PlotProvNoProv.jpeg}
\caption{Comparing the no-provenance vs provenance models. Both of these models include the forcing parameters. We compare model parameters on a 1:1 line (red dashed line) where the y-axis represents the model that excludes provenance and the x-axis depicts the model that includes the provenance parameters. `a' is the grand intercept for each species, `bcs' is the chilling slope for each species, `bf' is the forcing slope for each species  and `bt' is the time slope for each species.}
\label{fig:provNoProv}
\end{figure}


% Max temp
\begin{figure}[!ht]
\includegraphics[width=0.7\textwidth]{../../analyses/analyseSeedCues/provenance/figures/forcingComparisonMaxGermtemp.jpeg}
\caption{Comparing forcing vs no-forcing models color coded by the max temperature used in each study. We compare model parameters on a 1:1 line (red dashed line) where the x-axis represents the model that includes forcing and the y-axis depicts the model that excludes the forcing parameters. `a' is the grand intercept for each species, `a_prov' is the intercept for each provenance, `bcs' is the chilling slope for each species, `bcs_prov' is the chilling slope for each provenance, `bt' is the time slope for each species and `bt_prov' is the time slope for each provenance}
\label{fig:maxGermTemp}
\end{figure}

% Number of unique germination treatments
\begin{figure}[!ht]
\includegraphics[width=0.7\textwidth]{../../analyses/analyseSeedCues/provenance/figures/forcingComparisonUniqueGermtemp.jpeg}
\caption{Comparing forcing vs no-forcing models color coded by the number of unique germination temperature treatments in each study. We compare model parameters on a 1:1 line (red dashed line) where the x-axis represents the model that includes forcing and the y-axis depicts the model that excludes the forcing parameters. `a' is the grand intercept for each species, `a_prov' is the intercept for each provenance, `bcs' is the chilling slope for each species, `bcs_prov' is the chilling slope for each provenance, `bt' is the time slope for each species and `bt_prov' is the time slope for each provenance}
\label{fig:uniqueGermTemp}
\end{figure}

% Germ temp interval
\begin{figure}[!ht]
\includegraphics[width=0.7\textwidth]{../../analyses/analyseSeedCues/provenance/figures/forcingComparisonIntervGermtemp.jpeg}
\caption{Comparing forcing vs no-forcing models color coded by the temperature interval in the study. We compare model parameters on a 1:1 line (red dashed line) where the x-axis represents the model that includes forcing and the y-axis depicts the model that excludes the forcing parameters. `a' is the grand intercept for each species, `a_prov' is the intercept for each provenance, `bcs' is the chilling slope for each species, `bcs_prov' is the chilling slope for each provenance, `bt' is the time slope for each species. `bt_prov' is the time slope for each provenance}
\label{fig:germTempInterval}
\end{figure}




\begin{figure}[!ht]
\includegraphics[width=0.7\textwidth]{../../analyses/analyseSeedCues/provenance/figures/muPlotProv_bcsprov.pdf}
\caption{Chilling slope parameters} %emw11Aug: What model? 
\label{fig:muChilling}
\end{figure}

\begin{figure}[!ht]
\includegraphics[width=0.7\textwidth]{../../analyses/analyseSeedCues/provenance/figures/muPlotProv_bfprov.pdf}
\caption{Forcing slope parameters} %emw11Aug: What model? 
\label{fig:muForcing}
\end{figure}

\begin{figure}[!ht]
\includegraphics[width=0.7\textwidth]{../../analyses/analyseSeedCues/provenance/figures/muPlotProv_btprov.pdf}
\caption{Time slope parameters} %emw11Aug: What model? 
\label{fig:muTime}
\end{figure}

\begin{figure}[!ht]
\includegraphics[width=0.7\textwidth]{../../analyses/analyseSeedCues/provenance/figures/retrodictiveChecks/PPC_meanT.pdf}
\caption{General response curve across all species as a function of chilling (scaled). We averaged the contribution of time and included it in the response curve.}
\label{fig:respCurveChilling} %emw11Aug: What model? 
\end{figure}


\begin{figure}[!ht]
\includegraphics[width=0.7\textwidth]{../../analyses/analyseSeedCues/provenance/figures/retrodictiveChecks/PPC_meanC.pdf}
\caption{General response curve across all species as a function of time (scaled). We averaged the contribution of chilling and included it in the response curve.}
\label{fig:respCurveTime} %emw11Aug: What model? 
\end{figure}

\end{document}
