## Started 10 July 2024 ##
## By Dan, continued by Justin ##

## Updated 26 Jan 2025 by Mao ##

# Changing column names to better fit EGRET 

# Replacing all blanks with NA
d[d==""] <- NA

colnames(d)
colnames(d) <- c("rowID",
                 "pdfPageNumber",
                 "pdfTableNumber",
                 "genus",
                 "species",
                 "seedType",
                 "source.population",
                 "medium",
                 "pretreatmentDuration",
                 "pretreatmentHotWaterTemp",
                 "pretreatment",
                 "coldStratTemp",
                 "warmStratDuration",
                 "coldStratDuration",
                 "photoperiod",
                 "tempDay",
                 "tempNight",
                 "tempUnspecified",
                 "germDuration",
                 "reps",
                 "warmStratTemp",
                 "notes",
                 "latbi",
                 "chilling",
                 "chillDuration",
                 "scarifTypeGen",
                 "scarifTypeSpe",
                 "avgGerminationPercen",
                 "responseType",
                 "responseValue",
                 "responseVarClean",     
                 "pretreatmentMin",
                 "pretreatmentMax",
                 "coldStratDurMin",
                 "coldStratDurMax",
                 "photoperiodMin",
                 "photoperiodMax",
                 "tempDayMin",
                 "tempDayMax",
                 "tempNightMin",
                 "tempNightMax",
                 "germDurationMin",
                 "germDurationMax",
                 "samplesMin",
                 "samplesMax",
                 "chillDurationMin",
                 "chillDurationMax",
                 "responseValueMin",
                 "responseValueMax",
                 "responseValueAvg",
                 "pretreatmentAvg",
                 "coldStratDurAvg",
                 "photoperiodAvg",
                 "tempDayAvg",
                 "tempNightAvg",
                 "germDurationAvg",
                 "samplesAvg",
                 "chillDurationAvg")

d <- d[, c("rowID", "pdfPageNumber", "pdfTableNumber",
           "genus",
           "species","latbi",
           "seedType",
           "source.population",
           "medium",
           "pretreatmentDuration",
           "pretreatmentHotWaterTemp",
           "pretreatment","coldStratTemp","warmStratTemp", "warmStratDuration",
           "coldStratDuration",
           "photoperiod",
           "tempDay",
           "tempNight",
           "tempUnspecified",
           "germDuration",
           "reps","chilling",
           "chillDuration",
           "scarifTypeGen",
           "scarifTypeSpe",
           "avgGerminationPercen",
           "responseValue",
           "pretreatmentMin",
           "pretreatmentMax",
           "coldStratDurMin",
           "coldStratDurMax",
           "photoperiodMin",
           "photoperiodMax",
           "tempDayMin",
           "tempDayMax",
           "tempNightMin",
           "tempNightMax",
           "germDurationMin",
           "germDurationMax",
           "samplesMin",
           "samplesMax",
           "chillDurationMin",
           "chillDurationMax",
           "responseValueMin",
           "responseValueMax",
           "responseValueAvg",
           "pretreatmentAvg",
           "coldStratDurAvg",
           "photoperiodAvg",
           "tempDayAvg",
           "tempNightAvg",
           "germDurationAvg",
           "samplesAvg",
           "chillDurationAvg","notes")]
